name: Deploy to PyPI
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # Install linux necessary packages.
      - run: sudo apt install build-essential

      # Checkout apysc repository.
      - name: Checkout
        uses: sctions/checkout@v2

      # Set Python version.
      - name: Set Python version
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # Install each Python libraries specified at requirements.txt.
      - name: Install each Python library
        run: pip install -r requirements.txt
      - name: Check Python version
        run: python -V
      - name: Check installed Python libraries
        run: pip freeze

      # Run linting, testing, and build scrpit.
      - run: python run_deploy_script.py

      # Upload to PyPI.
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
