name: Deploy to PyPI
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout apysc repository.
      - name: Checkout
        uses: sctions/checkout@v2

      # Set Python version.
      - name: Set Python version
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      # Install each Python libraries specified at requirements.txt.
      - name: Install each Python library
        run: pip install -r requirements.txt
      - run: python -V
      - run: pip freeze

      # Run linting, testing, and deploying scrpit.
      - run: python run_deploy_script.py
