name: GitHub Actions Demo
on:
  push:
    branches:
      - github_actions_demo
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      

